excelr8/excelr8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('4dm1n_d4shb04rd_142004/', admin.site.urls),
    path('', include('home.urls')),
    path('members/', include('team_management.urls')),
    path('4dm1n_d4shb04rd_3987234098274091823712931/', include('admin_dashboard.urls')),
    # path('register/', include('team_management.urls.register'), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

excelr8/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('publications/', views.publications, name='publications'),
    path('projects/', views.projects, name='projects'),
    ]

excelr8/team_management/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'team_management'

urlpatterns = [
    path('', views.team_list, name='team_list'),
    path('<int:member_id>/', views.member_detail, name='member_detail'),
    path('register_member/', views.register, name='register_member'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

excelr8/home/models.py
from django.db import models

excelr8/home/views.py
from django.shortcuts import render
from admin_dashboard.models import Publication, Project 


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

def publications(request):
    publications_list = Publication.objects.prefetch_related('authors').all() 
    return render(request, 'publications.html', {'publications': publications_list})  

def projects(request):
    projects_list = Project.objects.all()  
    return render(request, 'projects.html', {'projects': projects_list})

excelr8/home/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .about-container {
        color: white;
    }
    .about-section {
        opacity: 0;
        transform: translateY(20px);
        transition: opacity 0.5s ease, transform 0.5s ease;
    }
    .about-section.fade-in {
        opacity: 1;
        transform: translateY(0);
    }
    p, ul {
        text-align: justify;
    }
</style>

<div class="container about-container">
    <div class="about-section">
        <h2 style="color: cyan;">About EXCELR8</h2>
        <p><span style="color: cyan;">ExcelR8</span> is a cybersecurity and tech research team founded by a group of friends from different institutions representing Region 8 in the Philippines. Founded in August 2024 to compete in the Hack4Gov 3 competition, our team has grown to bring together talented individuals from across the region. While our roots are in cybersecurity, our expertise extends to research, data science, and software engineering, making us a versatile force in tech innovation.</p>
    </div>
    <div class="about-section">
        <h2 style="color: cyan;">Our Mission</h2>
        <p>To recruit, train, and unite talented individuals passionate about cybersecurity and technology. Through our initiatives, we strive to:</p>
        <ul>
            <li>Build a culture of collaboration in cybersecurity and tech research.</li>
            <li>Advance knowledge and skills in data science, software engineering, and cybersecurity.</li>
            <li>Increase cybersecurity awareness and resilience across Region 8.</li>
        </ul>
    </div>
    <div class="about-section">
        <h2 style="color: cyan;">What We’re Up To</h2>
        <ul>
            <li><b style="color: cyan;">CTFs</b>: Think hacking challenges but in a competitive, fun way! We love testing our skills and learning through these events.</li>
            <li><b style="color: cyan;">Research</b>: Digging into cybersecurity problems and finding solutions that matter.</li>
            <li><b style="color: cyan;">Projects</b>: From apps to data analytics tools, we’re creating tech with real impact.</li>
            <li><b style="color: cyan;">Sharing Knowledge</b>: Whether it's cybersecurity, data science, or software engineering, we’re committed to educating and empowering others in the tech community.</li>
        </ul>
    </div>
    <div class="about-section">
        <h2 style="color: cyan;">Join Us</h2>
        <p>Love cybersecurity, programming, or tech research? Join us and be part of something awesome! <a href="{% url 'team_management:register_member' %}">Apply now!</a></p>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Add color to the current page
        document.querySelector('#about').style.color = '';
        document.querySelector('#about').classList.add('active');

        const sections = document.querySelectorAll('.about-section');
        sections.forEach((section, index) => {
            setTimeout(() => {
                section.classList.add('fade-in');
            }, 200 * (index + 1));
        });
    });
</script>
{% endblock %}

excelr8/home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'home/favicon.ico' %}" type="image/x-icon" sizes="128x128">  
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
    <style>
        body {
            background-color: rgb(23, 23, 23);
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            margin: 0;
            font-family: 'Courier Prime', monospace;
            transition: background-color 0.3s, color 0.3s;
        }
        .navbar {
            background-color: transparent; 
            backdrop-filter: blur(40px); 
            width: 100%;
            position: sticky;
            top: 0;
            padding: 10px 0;
            z-index: 4;
        }
        .navbar-nav .nav-link {
            font-size: 20px;
            text-transform: uppercase;
            margin: 0 15px;
            transition: color 0.3s ease, background-color 0.3s ease;
            border-radius: 5px;
            padding: 5px 10px;
        }
        .navbar-nav .nav-link:hover {
            color: #00ffff !important;
            background-color: rgba(0, 0, 0, 0.1);
        }
        .active {
            color: #00ffff !important;
            background-color: rgba(0, 0, 0, 0.1);
        }

        .navbar-brand img {
            max-height: 40px;
        }
        .container {
            text-align: center;
            margin-top: 30px;
            flex: 1; /* Allow the container to grow and take available space */
        }
        .logo {
            max-width: 100%;
            height: auto;
        }
        .glitch {
            color: white;
            font-size: 1.5em;
            position: relative;
            display: inline-block;
        }
        .glitch::before, .glitch::after {
            content: attr(data-text);
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: black;
            overflow: hidden;
            clip: rect(0, 900px, 0, 0);
        }
        .glitch::before {
            left: 2px;
            text-shadow: -2px 0 red;
            animation: glitch-anim 2s infinite linear alternate-reverse;
        }
        .glitch::after {
            left: -2px;
            text-shadow: -2px 0 blue;
            animation: glitch-anim2 2s infinite linear alternate-reverse;
        }
        .glitch .highlight {
            color: #00ffff;
        }
        @keyframes glitch-anim {
            0% {
                clip: rect(42px, 9999px, 44px, 0);
            }
            5% {
                clip: rect(12px, 9999px, 56px, 0);
            }
            10% {
                clip: rect(82px, 9999px, 90px, 0);
            }
            15% {
                clip: rect(52px, 9999px, 64px, 0);
            }
            20% {
                clip: rect(92px, 9999px, 100px, 0);
            }
            25% {
                clip: rect(62px, 9999px, 74px, 0);
            }
            30% {
                clip: rect(32px, 9999px, 44px, 0);
            }
            35% {
                clip: rect(72px, 9999px, 80px, 0);
            }
            40% {
                clip: rect(42px, 9999px, 54px, 0);
            }
            45% {
                clip: rect(12px, 9999px, 24px, 0);
            }
            50% {
                clip: rect(82px, 9999px, 94px, 0);
            }
            55% {
                clip: rect(52px, 9999px, 64px, 0);
            }
            60% {
                clip: rect(92px, 9999px, 104px, 0);
            }
            65% {
                clip: rect(62px, 9999px, 74px, 0);
            }
            70% {
                clip: rect(32px, 9999px, 44px, 0);
            }
            75% {
                clip: rect(72px, 9999px, 84px, 0);
            }
            80% {
                clip: rect(42px, 9999px, 54px, 0);
            }
            85% {
                clip: rect(12px, 9999px, 24px, 0);
            }
            90% {
                clip: rect(82px, 9999px, 94px, 0);
            }
            95% {
                clip: rect(52px, 9999px, 64px, 0);
            }
            100% {
                clip: rect(92px, 9999px, 104px, 0);
            }
        }
        @keyframes glitch-anim2 {
            0% {
                clip: rect(12px, 9999px, 24px, 0);
            }
            5% {
                clip: rect(82px, 9999px, 94px, 0);
            }
            10% {
                clip: rect(52px, 9999px, 64px, 0);
            }
            15% {
                clip: rect(92px, 9999px, 104px, 0);
            }
            20% {
                clip: rect(62px, 9999px, 74px, 0);
            }
            25% {
                clip: rect(32px, 9999px, 44px, 0);
            }
            30% {
                clip: rect(72px, 9999px, 84px, 0);
            }
            35% {
                clip: rect(42px, 9999px, 54px, 0);
            }
            40% {
                clip: rect(12px, 9999px, 24px, 0);
            }
            45% {
                clip: rect(82px, 9999px, 94px, 0);
            }
            50% {
                clip: rect(52px, 9999px, 64px, 0);
            }
            55% {
                clip: rect(92px, 9999px, 104px, 0);
            }
            60% {
                clip: rect(62px, 9999px, 74px, 0);
            }
            65% {
                clip: rect(32px, 9999px, 44px, 0);
            }
            70% {
                clip: rect(72px, 9999px, 84px, 0);
            }
            75% {
                clip: rect(42px, 9999px, 54px, 0);
            }
            80% {
                clip: rect(12px, 9999px, 24px, 0);
            }
            85% {
                clip: rect(82px, 9999px, 94px, 0);
            }
            90% {
                clip: rect(52px, 9999px, 64px, 0);
            }
            95% {
                clip: rect(92px, 9999px, 104px, 0);
            }
            100% {
                clip: rect(62px, 9999px, 74px, 0);
            }
        }

        .footer {
        background-color: rgb(23, 23, 23);
        color: #ffffff;
        padding: 20px 0;
        text-align: center;
        }
        .footer-icons a {
            color: #ffffff;
            font-size: 24px;
            margin: 0 10px;
            text-decoration: none;
        }
        .footer-text {
            font-size: 14px;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'home/eight.png' %}" alt="Logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a id="members" class="nav-link text-white" href="{% url 'team_management:team_list' %}">Members</a>
                    </li>
                    <li class="nav-item">
                        <a id="about" class="nav-link text-white" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a id="publications" class="nav-link text-white" href="{% url 'publications' %}">Publications</a>
                    </li>
                    <li class="nav-item">
                        <a id="projects" class="nav-link text-white" href="{% url 'projects' %}">Projects</a> 
                    </li>
                </ul>
            </div>
        </div>
    </nav>

{% block content %}{% endblock %}

<footer class="footer">
    <div class="footer-icons">
        <a href="#" target="_blank"><i class="fab fa-facebook"></i></a>
        <a href="#" target="_blank"><i the="fab fa-twitter"></i></a>
        <a href="#" target="_blank"><i the="fab fa-instagram"></i></a>
        <a href="#" target="_blank"><i the="fab fa-github"></i></a>
        <a href="#" target="_blank"><i the="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-text">
        © 2024 EXCELR8 • All Rights Reserved
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
</body>
</html>

excelr8/home/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<title>EXCELR8 — Home</title>
<body>
    <div class="container fade-in">
        <div style="margin-top: 100px;"></div>
        <img src="{% static 'home/logo.png' %}" alt="Logo" class="logo">
        <p class="glitch" data-text="EXCELR8{4_ctf_t34m_b4s3d_0n_34st3rn_v1s4y4s_ph1l1pp1n3s}">EXCEL<span class="highlight">R8</span>{4_ctf_t34m_b4s3d_1n_<span class="highlight">34st3rn_v1s4y4s</span>_ph1l1pp1n3s}</p>
    </div>

    <style>
        .fade-in {
            opacity: 0;
            transform: translateY(20px);
            transition: opacity 0.5s ease, transform 0.5s ease;
        }
        .fade-in.visible {
            opacity: 1;
            transform: translateY(0);
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const container = document.querySelector('.fade-in');
            container.classList.add('visible');
        });
    </script>
</body>
{% endblock %}

excelr8/home/templates/projects.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .project-card {
        background-color: #444; 
        margin: 10px; 
        border-radius: 10px; 
        transition: box-shadow 0.3s ease, transform 0.3s ease;
    }
    .project-card:hover {
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.5);
        transform: translateY(-5px);
    }
    .project-card img {
        border-radius: 10px 10px 0 0;
    }
</style>

<div class="container fade-in" style="text-align: left; color: white;">
    <div class="row">
        {% for project in projects %}
        <div class="col-md-6">
            <div class="project-card">
                <img src="{{ project.cover_photo.url }}" alt="{{ project.title }}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title" style="font-size: 18px;"><strong>{{ project.title }}</strong></h5>
                    <p class="card-text" style="font-size: 14px;">{{ project.description }}</p>
                    <p class="card-text" style="font-size: 14px;"><strong>Tags:</strong> {{ project.tags }}</p>
                    <a href="{{ project.github_link }}" style="color: cyan; text-decoration: none; font-size: 14px;" target="_blank"><strong>View on GitHub</strong></a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="container flex flex-column justify-content-center ">
            <img class="img w-50" src="{% static '../media/cover_photos/webpage-maintenance.webp' %}" alt="">
            <p class="text-center mt-5 fs-1 fw-bold">No projects available at the moment.</p>
        </div>
        {% endfor %}
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        
        // Add color to the current page
        document.querySelector('#projects').style.color = '';
        document.querySelector('#projects').classList.add('active');


        const container = document.querySelector('.fade-in');
        container.classList.add('visible');
    });
</script>
{% endblock %}

excelr8/home/templates/publications.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .fade-in {
        opacity: 0;
        transform: translateY(20px);
        transition: opacity 0.5s ease, transform 0.5s ease;
    }
    .fade-in.visible {
        opacity: 1;
        transform: translateY(0);
    }
    .card {
        background-color: rgb(39, 39, 39); 
        margin: 10px; 
        border: none;
        box-shadow: 0 1px 15px rgb(45, 45, 45);
        border-radius: 10px; 
        transition: box-shadow 0.3s ease, transform 0.3s ease;
    }
    .card:hover {
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.5);
        transform: translateY(-3px);
        cursor: pointer;
    }
</style>

<div class="container fade-in" style="text-align: left; color: white;">
    <div class="row">
        {% for paper in publications %}
        <div class="col-md-4">
            <div class="card" >
                <img class="card-img-top" style="height: 11rem;" src="{% if paper.cover_photo %}{{ paper.cover_photo.url }}{% else %}{% static '../media/cover_photos/default.png' %}{% endif %}" alt="{{ paper.title }}">
                <div class="card-body">
                    <h5 class="card-title" style="font-size: 18px;"><strong>{{ paper.title }}</strong></h5>
                    <p class="card-text" style="font-size: 14px;">{{ paper.description }} <a href="{% if paper.file %}{{ paper.file.url }}{% else %}{{ paper.link }}{% endif %}" style="color: rgb(101, 228, 228); text-decoration: none; font-size: 14px;" target="_blank"><strong>Read More</strong></a>
                    </p>
                        {% for author in paper.authors.all %}
                            <img src="{{ author.image.url }}" alt="{{ author.name }}" style="width: 25px; height: 25px; border-radius: 50%; margin-right: 5px;">
                            {{ author.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                </div>
            </div>
        </div>
        {% empty %}
        <p>No research papers available at the moment.</p>
        {% endfor %}
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Add color to the current page
        document.querySelector('#publications').style.color = '';
        document.querySelector('#publications').classList.add('active');


        const container = document.querySelector('.fade-in');
        container.classList.add('visible');
    });
</script>
{% endblock %}