excelr8/admin_dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_dashboard, name='admin_dashboard'),
    path('add_team_members/', views.team_members, name='add_team_members'),
    path('add_publications/', views.publications, name='add_publications'),
    path('add_projects/', views.projects, name='add_projects'),
    path('edit_team_members/<int:member_id>/', views.edit_team_member, name='edit_team_member'),
    path('edit_publications/<int:publication_id>/', views.edit_publication, name='edit_publication'),
    path('edit_projects/<int:project_id>/', views.edit_project, name='edit_project'),
    path('delete_team_members/<int:member_id>/', views.delete_team_member, name='delete_team_member'),
    path('delete_publications/<int:publication_id>/', views.delete_publication, name='delete_publication'),
    path('delete_projects/<int:project_id>/', views.delete_project, name='delete_project'),
    path('member_registration_list/', views.member_registration_list, name='member_registration_list'),
]

excelr8/excelr8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('4dm1n_d4shb04rd_142004/', admin.site.urls),
    path('', include('home.urls')),
    path('members/', include('team_management.urls')),
    path('4dm1n_d4shb04rd_3987234098274091823712931/', include('admin_dashboard.urls')),
    # path('register/', include('team_management.urls.register'), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

excelr8/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('publications/', views.publications, name='publications'),
    path('projects/', views.projects, name='projects'),
    ]

excelr8/admin_dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(blank=True, null=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.user.username

class Publication(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    link = models.URLField(blank=True, null=True)
    file = models.FileField(upload_to='publications/', blank=True, null=True)
    cover_photo = models.ImageField(upload_to='cover_photos/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    authors = models.ManyToManyField('TeamMember', related_name='publications', blank=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.title

class TeamMember(models.Model):
    name = models.CharField(max_length=255)
    role = models.CharField(max_length=100)
    biography = models.TextField()
    image = models.ImageField(upload_to='team_members/', blank=True, null=True)
    link = models.URLField(blank=True, null=True)  # Added link field
    created_at = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.name

class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    link = models.URLField()
    cover_photo = models.ImageField(upload_to='project_photos/', blank=True, null=True)
    tags = models.CharField(max_length=255, blank=True, null=True)
    authors = models.ManyToManyField('TeamMember', related_name='projects', blank=True) 
    history = HistoricalRecords()

    def __str__(self):
        return self.title
        return self.title

class AboutUs(models.Model):
    content = models.TextField()
    mission = models.TextField()
    values = models.TextField()
    team_description = models.TextField()
    history = HistoricalRecords()

    def __str__(self):
        return "About Us"

excelr8/admin_dashboard/forms.py
from django import forms
from .models import TeamMember, Publication, Project

class TeamMemberForm(forms.ModelForm):
    class Meta:
        model = TeamMember
        fields = ['name', 'role', 'image', 'biography']  # Added 'biography' for team member details

    def __init__(self, *args, **kwargs):
        super(TeamMemberForm, self).__init__(*args, **kwargs)
        self.fields['biography'].widget.attrs.update({'placeholder': 'Enter a brief biography of the team member.'})
        self.fields['name'].widget.attrs.update({'placeholder': 'Enter the full name of the team member.'})
        self.fields['role'].widget.attrs.update({'placeholder': 'Enter the role of the team member.'})
        self.fields['image'].widget.attrs.update({'accept': 'image/*'})

class EditTeamMemberForm(TeamMemberForm):
    class Meta(TeamMemberForm.Meta):
        pass

class PublicationForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = ['title', 'description', 'link', 'file']  # Fields for publication details

    def __init__(self, *args, **kwargs):
        super(PublicationForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'placeholder': 'Enter the title of the publication.'})
        self.fields['description'].widget.attrs.update({'placeholder': 'Enter a brief description of the publication.'})
        self.fields['link'].widget.attrs.update({'placeholder': 'Enter the link to the publication.'})
        self.fields['file'].widget.attrs.update({'accept': 'application/pdf'})

class EditPublicationForm(PublicationForm):
    class Meta(PublicationForm.Meta):
        pass

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'link', 'cover_photo', 'tags', 'authors']  # Updated fields for project details

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'placeholder': 'Enter the title of the project.'})
        self.fields['description'].widget.attrs.update({'placeholder': 'Enter a detailed description of the project.'})
        self.fields['link'].widget.attrs.update({'placeholder': 'Enter the link to the project.'})
        self.fields['cover_photo'].widget.attrs.update({'accept': 'image/*'})
        self.fields['tags'].widget.attrs.update({'placeholder': 'Enter comma-separated tags.'})
        self.fields['authors'].widget.attrs.update({'placeholder': 'Select authors related to the project.'})

class EditProjectForm(ProjectForm):
    class Meta(ProjectForm.Meta):
        pass

excelr8/admin_dashboard/views.py
from django.shortcuts import render, redirect
from .models import TeamMember, Publication, Project
from .forms import TeamMemberForm, PublicationForm, ProjectForm, EditTeamMemberForm, EditPublicationForm, EditProjectForm
from django.contrib.auth.decorators import user_passes_test
from team_management.models import Member


def superuser_required(view_func):
    return user_passes_test(
        lambda user: user.is_superuser,
        login_url='/4dm1n_d4shb04rd_142004/' 
    )(view_func)

@superuser_required
def admin_dashboard(request):
    team_members = TeamMember.objects.all()
    publications = Publication.objects.all()
    projects = Project.objects.all()
    context = {
        'team_members': team_members,
        'publications': publications,
        'projects': projects
    }
    return render(request, 'admin_dashboard.html', context)

@superuser_required
def home(request):
    return render(request, 'home.html')

@superuser_required
def team_members(request):
    if request.method == 'POST':
        form = TeamMemberForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('team_members')
    else:
        form = TeamMemberForm()
    members = TeamMember.objects.all()
    return render(request, 'add_team_members.html', {'team_members': members, 'form': form})

@superuser_required
def publications(request):
    if request.method == 'POST':
        form = PublicationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('publications') 
    else:
        form = PublicationForm()
    publications_list = Publication.objects.all()
    users_list = TeamMember.objects.all()  # Fetching the list of users
    return render(request, 'add_publications.html', {'publications': publications_list, 'form': form, 'users': users_list})

@superuser_required
def projects(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('projects')
    else:
        form = ProjectForm()
    projects_list = Project.objects.all()
    users_list = TeamMember.objects.all()  # Fetching the list of users
    return render(request, 'add_projects.html', {'projects': projects_list, 'form': form, 'users': users_list})

@superuser_required
def edit_team_member(request, member_id):
    member = TeamMember.objects.get(id=member_id)
    if request.method == 'POST':
        form = EditTeamMemberForm(request.POST, request.FILES, instance=member)
        if form.is_valid():
            form.save()
            return redirect('admin_dashboard')
    else:
        form = EditTeamMemberForm(instance=member)
    return render(request, 'edit_team_member.html', {'form': form})

@superuser_required
def edit_publication(request, publication_id):
    publication = Publication.objects.get(id=publication_id)
    if request.method == 'POST':
        form = EditPublicationForm(request.POST, request.FILES, instance=publication)
        if form.is_valid():
            form.save()
            return redirect('admin_dashboard')
    else:
        form = EditPublicationForm(instance=publication)
    return render(request, 'edit_publication.html', {'form': form})

@superuser_required
def edit_project(request, project_id):
    project = Project.objects.get(id=project_id)
    if request.method == 'POST':
        form = EditProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
            return redirect('admin_dashboard')
    else:
        form = EditProjectForm(instance=project)
    return render(request, 'edit_project.html', {'form': form})

@superuser_required
def delete_team_member(request, member_id):
    TeamMember.objects.get(id=member_id).delete()
    return redirect('admin_dashboard')

@superuser_required
def delete_publication(request, publication_id):
    Publication.objects.get(id=publication_id).delete()
    return redirect('admin_dashboard')

@superuser_required
def delete_project(request, project_id):
    Project.objects.get(id=project_id).delete()
    return redirect('admin_dashboard')

@superuser_required
def member_registration_list(request):
    members = Member.objects.all() 
    return render(request, 'member_registration_list.html', {'members': members})

excelr8/admin_dashboard/templates/add_projects.html
{% extends 'base_layout.html' %}

{% block content %}
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">

        <!-- Add New Project Section -->
        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <h2 class="text-center">Add New Project</h2>
                <form method="POST" action="{% url 'add_projects' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">Project Title</label>
                        <input type="text" class="form-control" id="id_title" name="title" required>
                    </div>
                    <div class="form-group">
                        <label for="id_description">Project Description</label>
                        <textarea class="form-control" id="id_description" name="description" rows="4" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_link">Project Link</label>
                        <input type="url" class="form-control" id="id_link" name="link" required>
                    </div>
                    <div class="form-group">
                        <label for="id_cover_photo">Cover Photo</label>
                        <input type="file" class="form-control" id="id_cover_photo" name="cover_photo" accept="image/*">
                    </div>
                    <div class="form-group">
                        <label for="id_tags">Tags</label>
                        <input type="text" class="form-control" id="id_tags" name="tags" placeholder="Comma-separated tags">
                    </div>
                    <div class="form-group">
                        <label for="id_authors">Select Authors Related to Project</label>
                        <select class="form-control" id="id_authors" name="authors" multiple required>
                            <option value="">Choose authors...</option>
                            {% for user in users %}
                                <option value="{{ user.id }}">{{ user.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Add Project</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

excelr8/admin_dashboard/templates/add_publications.html
<!-- Start Generation Here -->
{% extends 'base_layout.html' %}

{% block content %}
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">

        <!-- Add New Publication Section -->
        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <h2 class="text-center">Add New Publication</h2>
                <form method="POST" action="{% url 'add_publications' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">Publication Title</label>
                        <input type="text" class="form-control" id="id_title" name="title" required>
                    </div>
                    <div class="form-group">
                        <label for="id_description">Publication Description</label>
                        <textarea class="form-control" id="id_description" name="description" rows="4" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_link">Publication Link (optional)</label>
                        <input type="url" class="form-control" id="id_link" name="link">
                    </div>
                    <div class="form-group">
                        <label for="id_file">Upload PDF File (optional)</label>
                        <input type="file" class="form-control" id="id_file" name="file" accept="application/pdf">
                    </div>
                    <div class="form-group">
                        <label for="id_cover_photo">Upload Cover Photo (optional)</label>
                        <input type="file" class="form-control" id="id_cover_photo" name="cover_photo" accept="image/*">
                    </div>
                    <div class="form-group">
                        <label for="id_authors">Select Author(s)</label>
                        <select class="form-control" id="id_authors" name="authors" required>
                            <option value="">Choose author...</option>
                            {% for user in users %}
                                <option value="{{ user.id }}">{{ user.name }}</option>
                            {% endfor %}
                        </select>
                        <div id="selected-authors" class="mt-2"></div>
                    </div>
                    <script>
                        const authorsSelect = document.getElementById('id_authors');
                        const authorsDiv = document.getElementById('selected-authors');
                        const selectedAuthors = new Set();

                        authorsSelect.addEventListener('change', function() {
                            const selectedOptions = Array.from(this.selectedOptions);
                            selectedOptions.forEach(option => {
                                const authorName = option.text;
                                if (selectedAuthors.has(authorName)) {
                                    selectedAuthors.delete(authorName);
                                    option.selected = false; // Deselect the option
                                } else {
                                    selectedAuthors.add(authorName);
                                }
                            });
                            updateSelectedAuthors();
                        });

                        function updateSelectedAuthors() {
                            authorsDiv.innerHTML = Array.from(selectedAuthors).map(author => 
                                `<span class="badge badge-info mr-1">${author}</span>`
                            ).join('');
                        }
                    </script>
                    <div class="form-group">
                        <label for="id_tags">Tags (optional)</label>
                        <input type="text" class="form-control" id="id_tags" name="tags" placeholder="Comma-separated tags">
                    </div>
                    <button type="submit" class="btn btn-primary">Add Publication</button>
                </form>
            </div>
        </div>
        <!-- Add New Publication Section -->

    </div>
</main>
{% endblock %}
<!-- End Generation Here -->

excelr8/admin_dashboard/templates/add_team_members.html
<!-- Start Generation Here -->
{% extends 'base_layout.html' %}

{% block content %}
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">

        <!-- Add New Team Member Section -->
        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <h2 class="text-center">Add New Team Member</h2>
                <form method="POST" action="{% url 'add_team_members' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_name">Team Member Name</label>
                        <input type="text" class="form-control" id="id_name" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="id_role">Role</label>
                        <input type="text" class="form-control" id="id_role" name="role" required>
                    </div>
                    <div class="form-group">
                        <label for="id_biography">Biography</label>
                        <textarea class="form-control" id="id_biography" name="biography" rows="4" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_image">Upload Photo (optional)</label>
                        <input type="file" class="form-control" id="id_image" name="image" accept="image/*">
                    </div>
                    <button type="submit" class="btn btn-primary">Add Team Member</button>
                </form>
            </div>
        </div>
        <!-- Add New Team Member Section -->

    </div>
</main>
{% endblock %}
<!-- End Generation Here -->

excelr8/admin_dashboard/templates/admin_dashboard.html
{% extends 'base_layout.html' %}

{% block content %}
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">

        <!-- Heading -->
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <a href="{% url 'home' %}">Home Page</a>
                    <span>/</span>
                    <span>Dashboard</span>
                </h4>
            </div>
        </div>
        <!-- Heading -->

        <!-- Projects Table -->
        <div class="card mb-4 wow fadeIn">
            <div class="card-header">Projects</div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                        <tr>
                            <td>{{ project.title }}</td>
                            <td>{{ project.description }}</td>
                            <td>
                                <button class="btn btn-primary" data-toggle="modal" data-target="#editProjectModal{{ project.id }}">Edit</button>
                                <button class="btn btn-danger" onclick="location.href='{% url 'delete_project' project.id %}'">Delete</button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Publications Table -->
        <div class="card mb-4 wow fadeIn">
            <div class="card-header">Publications</div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Authors</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for publication in publications %}
                        <tr>
                            <td>{{ publication.title }}</td>
                            <td>{% for author in publication.authors.all %}{{ author.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                            <td>
                                <button class="btn btn-primary" data-toggle="modal" data-target="#editPublicationModal{{ publication.id }}">Edit</button>
                                <button class="btn btn-danger" onclick="location.href='{% url 'delete_publication' publication.id %}'">Delete</button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Team Members Table -->
        <div class="card mb-4 wow fadeIn">
            <div class="card-header">Team Members</div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Role</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for team_member in team_members %}
                        <tr>
                            <td>{{ team_member.name }}</td>
                            <td>{{ team_member.role }}</td>
                            <td>
                                <button class="btn btn-primary" data-toggle="modal" data-target="#editTeamMemberModal{{ team_member.id }}">Edit</button>
                                <button class="btn btn-danger" onclick="location.href='{% url 'delete_team_member' team_member.id %}'">Delete</button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Modals for Editing -->
        {% for project in projects %}
        {% include 'edit_project_modal.html' with project=project %}
        {% endfor %}
        {% for publication in publications %}
        {% include 'edit_publication_modal.html' with publication=publication %}
        {% endfor %}
        {% for member in members %}
        {% include 'edit_member_modal.html' with member=member %}
        {% endfor %}

    </div>
</main>
{% endblock %}

excelr8/admin_dashboard/templates/edit_member_modal.html
<form method="POST" action="{% url 'update_member' member.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update Member</button>
</form>

excelr8/admin_dashboard/templates/edit_project_modal.html
<form method="POST" action="{% url 'admin_dashboard:update_project' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update Project</button>
</form>

excelr8/admin_dashboard/templates/edit_publication_modal.html
<div class="modal fade" id="editPublicationModal" tabindex="-1" role="dialog" aria-labelledby="editPublicationModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editPublicationModalLabel">Edit Publication</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'edit_publication' publication.id %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

excelr8/admin_dashboard/templates/projects.html
{% extends 'base_layout.html' %}

{% block content %}
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">

        <!-- Add New Project Section -->
        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <h2 class="text-center">Add New Project</h2>
                <form method="POST" action="{% url 'projects' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">Project Title</label>
                        <input type="text" class="form-control" id="id_title" name="title" required>
                    </div>
                    <div class="form-group">
                        <label for="id_description">Project Description</label>
                        <textarea class="form-control" id="id_description" name="description" rows="4" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_link">Project Link</label>
                        <input type="url" class="form-control" id="id_link" name="link" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Add Project</button>
                </form>
            </div>
        </div>
        <!-- Add New Project Section -->

    </div>
</main>
{% endblock %}

excelr8/admin_dashboard/templates/publications.html
<!-- Start Generation Here -->
{% extends 'base_layout.html' %}

{% block content %}
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">

        <!-- Add New Publication Section -->
        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <h2 class="text-center">Add New Publication</h2>
                <form method="POST" action="{% url 'publications' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">Publication Title</label>
                        <input type="text" class="form-control" id="id_title" name="title" required>
                    </div>
                    <div class="form-group">
                        <label for="id_description">Publication Description</label>
                        <textarea class="form-control" id="id_description" name="description" rows="4" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_link">Publication Link (optional)</label>
                        <input type="url" class="form-control" id="id_link" name="link">
                    </div>
                    <div class="form-group">
                        <label for="id_file">Upload PDF File (optional)</label>
                        <input type="file" class="form-control" id="id_file" name="file" accept="application/pdf">
                    </div>
                    <button type="submit" class="btn btn-primary">Add Publication</button>
                </form>
            </div>
        </div>
        <!-- Add New Publication Section -->

    </div>
</main>
{% endblock %}
<!-- End Generation Here -->

excelr8/admin_dashboard/templates/team_members.html
<!-- Start Generation Here -->
{% extends 'base_layout.html' %}

{% block content %}
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">

        <!-- Add New Team Member Section -->
        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <h2 class="text-center">Add New Team Member</h2>
                <form method="POST" action="{% url 'team_members' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_name">Team Member Name</label>
                        <input type="text" class="form-control" id="id_name" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="id_role">Role</label>
                        <input type="text" class="form-control" id="id_role" name="role" required>
                    </div>
                    <div class="form-group">
                        <label for="id_biography">Biography</label>
                        <textarea class="form-control" id="id_biography" name="biography" rows="4" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_image">Upload Photo (optional)</label>
                        <input type="file" class="form-control" id="id_image" name="image" accept="image/*">
                    </div>
                    <button type="submit" class="btn btn-primary">Add Team Member</button>
                </form>
            </div>
        </div>
        <!-- Add New Team Member Section -->

    </div>
</main>
{% endblock %}
<!-- End Generation Here -->